### ISSUE TITLE
Displacements in God Room

### ISSUE THREAD

**Issue by maggotstf2** [KoxSosen/hutfmap#3]
![image](https://user-images.githubusercontent.com/52328022/102635604-dc5b6400-4153-11eb-92c6-e2a03ff84796.png)
![image](https://user-images.githubusercontent.com/52328022/102635638-e8472600-4153-11eb-89a8-3bc0fef3b237.png)
![image](https://user-images.githubusercontent.com/52328022/102635654-ee3d0700-4153-11eb-86ef-1ca1bcd273ab.png)
![image](https://user-images.githubusercontent.com/52328022/102635671-f39a5180-4153-11eb-9867-fcdb0595e350.png)

**Comment by KoxSosen** [comment]
új képeket tundál felrakni? Ezeken nem látszik lul

**Comment by maggotstf2** [comment]
elvileg fixed, úgyhogy ezt lezárom
